[project]
name = "site_to_markdown"
version = "0.1.0"
description = "A tool to scrape a website and convert it to markdown."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scrapy",
    "readability-lxml",
    "markdownify",
    "lxml[html_clean]",
    "langdetect",
]
